services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: job-zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: job-kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://job-kafka:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  spark:
    image: apache/spark:3.5.1
    container_name: job-spark
    user: root

    volumes:
      - ./spark:/app/spark

    depends_on:
      - kafka
      - postgres

    ports:
      - "4040:4040"

    command: tail -f /dev/null


  postgres:

    image: postgres:15

    container_name: job-postgres

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

      POSTGRES_DB: jobs_db


    ports:

      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jobs_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s


    volumes:

      - postgres_data:/var/lib/postgresql/data
  
  airflow:
    image: apache/airflow:2.10.5
    container_name: job-airflow

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/jobs_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    ports:
      - "8081:8080"
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create \
      --username admin \
      --password admin \
      --firstname Admin \
      --lastname User \
      --role Admin \
      --email admin@test.com || true;
      airflow scheduler &
      exec airflow webserver
      "
  dashboard:
    image: python:3.11
    container_name: job-dashboard
    working_dir: /app

    volumes:
      - ./dashboard:/app
      - ./requirements-dashboard.txt:/requirements.txt
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      streamlit run app.py
      --server.address=0.0.0.0
      "

volumes:

  postgres_data: